Repository ucsd-cse125-sp24/group3, pull requests merged in 2024-05, with the labels that each got.

#66 Maze Environment Loading From File
  config.json
  include/server/game/constants.hpp
  include/server/game/grid.hpp
  include/server/game/gridcell.hpp
  include/server/game/servergamestate.hpp
  include/shared/game/sharedgamestate.hpp
  include/shared/network/constants.hpp
  include/shared/utilities/config.hpp
  include/shared/utilities/root_path.hpp
  maps/default_maze.maze
  maps/gil_test.maze
  maps/maze1.maze
  maps/maze2.maze
  maps/tyler_test.maze
  src/client/client.cpp
  src/client/cube.cpp
  src/debugger/main.cpp
  src/server/CMakeLists.txt
  src/server/game/grid.cpp
  src/server/game/gridcell.cpp
  src/server/game/servergamestate.cpp
  src/server/server.cpp
  src/shared/CMakeLists.txt
  src/shared/game/sharedobject.cpp
  src/shared/network/session.cpp
  src/shared/utilities/config.cpp
  src/shared/utilities/root_path.cpp
Labels: enhancement, Gameplay

#80 Updated `ObjectManager` and Slight `Object`-Derived Class Refactoring
  include/debugger/debugger.hpp
  include/server/game/creature.hpp
  include/server/game/enemy.hpp
  include/server/game/item.hpp
  include/server/game/object.hpp
  include/server/game/objectmanager.hpp
  include/server/game/player.hpp
  include/server/game/servergamestate.hpp
  include/shared/game/sharedobject.hpp
  src/server/game/objectmanager.cpp
  src/server/game/servergamestate.cpp
  src/server/server.cpp
Labels: bug, enhancement, Gameplay

#93 Refactor/object position dimensions
  config.json
  include/debugger/debugger.hpp
  include/server/game/boxcollider.hpp
  include/server/game/collider.hpp
  include/server/game/object.hpp
  include/server/game/servergamestate.hpp
  include/server/game/spherecollider.hpp
  include/shared/game/sharedmodel.hpp
  include/shared/game/sharedobject.hpp
  src/client/client.cpp
  src/server/CMakeLists.txt
  src/server/game/boxcollider.cpp
  src/server/game/collider.cpp
  src/server/game/creature.cpp
  src/server/game/enemy.cpp
  src/server/game/object.cpp
  src/server/game/player.cpp
  src/server/game/servergamestate.cpp
  src/server/game/solidsurface.cpp
  src/server/game/spherecollider.cpp
  src/server/server.cpp
  src/shared/game/sharedobject.cpp
Labels: enhancement, Must have, Gameplay

#96 More Traps
  config.json
  include/server/game/arrowtrap.hpp
  include/server/game/fakewall.hpp
  include/server/game/fireballtrap.hpp
  include/server/game/floorspike.hpp
  include/server/game/gridcell.hpp
  include/server/game/item.hpp
  include/server/game/object.hpp
  include/server/game/objectmanager.hpp
  include/server/game/projectile.hpp
  include/server/game/servergamestate.hpp
  include/server/game/spiketrap.hpp
  include/server/game/trap.hpp
  include/shared/game/sharedobject.hpp
  include/shared/game/stat.hpp
  include/shared/network/constants.hpp
  maps/room.maze
  maps/tylers_hellhole.maze
  src/client/camera.cpp
  src/client/client.cpp
  src/server/CMakeLists.txt
  src/server/game/arrowtrap.cpp
  src/server/game/fakewall.cpp
  src/server/game/fireballtrap.cpp
  src/server/game/floorspike.cpp
  src/server/game/gridcell.cpp
  src/server/game/item.cpp
  src/server/game/objectmanager.cpp
  src/server/game/player.cpp
  src/server/game/potion.cpp
  src/server/game/projectile.cpp
  src/server/game/servergamestate.cpp
  src/server/game/spiketrap.cpp
  src/server/game/trap.cpp
  src/server/lobbybroadcaster.cpp
Labels: MVP, Gameplay

#99 Optimize/collision detection
  include/server/game/grid.hpp
  include/server/game/object.hpp
  include/server/game/objectmanager.hpp
  include/server/game/servergamestate.hpp
  include/shared/utilities/custom_hash.hpp
  maps/big_maze.maze
  src/server/game/fireballtrap.cpp
  src/server/game/grid.cpp
  src/server/game/objectmanager.cpp
  src/server/game/servergamestate.cpp
Labels: enhancement, Gameplay

#106 Feat/victory condition
  config.json
  include/client/gui/gui.hpp
  include/server/game/constants.hpp
  include/server/game/exit.hpp
  include/server/game/gridcell.hpp
  include/server/game/item.hpp
  include/server/game/objectmanager.hpp
  include/server/game/orb.hpp
  include/server/game/servergamestate.hpp
  include/shared/game/constants.hpp
  include/shared/game/sharedgamestate.hpp
  include/shared/game/sharedobject.hpp
  include/shared/utilities/config.hpp
  maps/rooms/10x10/basic.exit
  maps/rooms/10x10/basic.spawn
  maps/rooms/10x10/basic1.exit
  maps/rooms/10x10/basic2.exit
  maps/test/itemRoom.maze
  maps/test/maze6.maze
  src/client/client.cpp
  src/client/gui/gui.cpp
  src/debugger/main.cpp
  src/server/CMakeLists.txt
  src/server/game/exit.cpp
  src/server/game/gridcell.cpp
  src/server/game/objectmanager.cpp
  src/server/game/orb.cpp
  src/server/game/player.cpp
  src/server/game/servergamestate.cpp
  src/server/server.cpp
  src/shared/game/sharedgamestate.cpp
  src/shared/utilities/config.cpp
Labels: enhancement, MVP, Must have, Gameplay, UI

#89 The Dungeon Master
  .gitignore
  config.json
  include/client/camera.hpp
  include/client/client.hpp
  include/client/cube.hpp
  include/client/model.hpp
  include/client/renderable.hpp
  include/server/game/constants.hpp
  include/server/game/dungeonmaster.hpp
  include/server/game/gridcell.hpp
  include/server/game/object.hpp
  include/server/game/objectmanager.hpp
  include/server/game/servergamestate.hpp
  include/server/game/solidsurface.hpp
  include/server/game/trap.hpp
  include/shared/game/celltype.hpp
  include/shared/game/constants.hpp
  include/shared/game/event.hpp
  include/shared/game/sharedmodel.hpp
  include/shared/game/sharedobject.hpp
  include/shared/network/constants.hpp
  include/shared/network/packet.hpp
  include/shared/network/session.hpp
  include/shared/utilities/typedefs.hpp
  maps/rooms/10x10/basic.orb
  src/client/camera.cpp
  src/client/client.cpp
  src/client/cube.cpp
  src/client/gui/gui.cpp
  src/client/gui/widget/textinput.cpp
  src/client/model.cpp
  src/client/shaders/dm_cube.frag
  src/client/shaders/solidsurface.vert
  src/client/tests/bbox.cpp
  src/server/CMakeLists.txt
  src/server/game/dungeonmaster.cpp
  src/server/game/grid.cpp
  src/server/game/gridcell.cpp
  src/server/game/object.cpp
  src/server/game/objectmanager.cpp
  src/server/game/orb.cpp
  src/server/game/servergamestate.cpp
  src/server/game/solidsurface.cpp
  src/server/game/spiketrap.cpp
  src/server/game/trap.cpp
  src/server/server.cpp
  src/shared/network/session.cpp
  src/shared/utilities/config.cpp
Labels: MVP, Must have, Gameplay

#150 Added lobby system
  CMakeLists.txt
  CppProperties.json
  config.json
  dependencies/boost/CMakeLists.txt
  include/client/client.hpp
  include/client/gui/gui.hpp
  include/client/gui/widget/dyntext.hpp
  include/client/gui/widget/empty.hpp
  include/client/gui/widget/type.hpp
  include/server/game/objectmanager.hpp
  include/server/game/servergamestate.hpp
  include/shared/game/event.hpp
  include/shared/game/sharedgamestate.hpp
  include/shared/utilities/smartvector.hpp
  src/client/client.cpp
  src/client/gui/CMakeLists.txt
  src/client/gui/gui.cpp
  src/client/gui/widget/dyntext.cpp
  src/client/gui/widget/empty.cpp
  src/server/game/objectmanager.cpp
  src/server/game/servergamestate.cpp
  src/server/lobbybroadcaster.cpp
  src/server/server.cpp
  src/shared/game/sharedgamestate.cpp
Labels: enhancement, Must have, Gameplay, UI

#163 update GUI
  CppProperties.json
  assets/imgs/blade.png
  assets/imgs/compass.png
  assets/imgs/compasses/compass_0.png
  assets/imgs/compasses/compass_180.png
  assets/imgs/compasses/compass_270.png
  assets/imgs/compasses/compass_90.png
  assets/imgs/dmBackground.png
  assets/imgs/dmEventBG.png
  assets/imgs/dm_left.png
  assets/imgs/dm_middle.png
  assets/imgs/dm_right.png
  assets/imgs/dm_selected.png
  assets/imgs/eventBG.png
  assets/imgs/itemBackground.png
  assets/imgs/left.png
  assets/imgs/manabar.png
  assets/imgs/manatick_empty.png
  assets/imgs/manatick_full.png
  assets/imgs/middle.png
  assets/imgs/needle.png
  assets/imgs/right.png
  assets/imgs/selected_middle.png
  config.json
  include/client/gui/font/font.hpp
  include/client/gui/gui.hpp
  include/client/gui/img/img.hpp
  include/server/game/constants.hpp
  include/server/game/dungeonmaster.hpp
  include/server/game/player.hpp
  include/server/game/servergamestate.hpp
  include/server/game/spawner.hpp
  include/shared/game/sharedobject.hpp
  src/client/gui/gui.cpp
  src/client/gui/imgs/img.cpp
  src/server/game/dungeonmaster.cpp
  src/server/game/player.cpp
  src/server/game/servergamestate.cpp
  src/server/game/spawner.cpp
  src/server/game/weapon.cpp
Labels: enhancement, Nice to have, UI
